# Generated by Django 3.0.3 on 2020-04-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='skid',
            field=models.TextField(),
        ),
    ]
