# Generated by Django 3.0.3 on 2020-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsj', '0002_auto_20200408_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_email',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField()),
                ('verif', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('birth', models.DateField()),
                ('sex', models.IntegerField()),
                ('tell', models.CharField(max_length=11)),
                ('order', models.TextField()),
                ('cart', models.TextField()),
                ('header_photo', models.ImageField(upload_to='')),
                ('nick_name', models.CharField(max_length=18)),
            ],
        ),
    ]
