# Generated by Django 3.0.3 on 2020-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsj', '0003_send_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_photo',
            field=models.TextField(),
        ),
    ]
