# Generated by Django 3.0.3 on 2020-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsj', '0004_auto_20200411_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
