# Generated by Django 3.0.3 on 2020-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsj', '0005_user_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_email',
            name='verif',
            field=models.CharField(max_length=37),
        ),
    ]
