# Generated by Django 3.0.3 on 2020-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsj', '0006_auto_20200413_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_email',
            name='static',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
